//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.05 at 12:57:53 PM CST 
//

package shop;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import lombok.Data;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "head", "body", "signature" })
@XmlRootElement(name = "ROOT")
@Data
public class Request1 {

    @XmlElement(name = "HEAD", required = true)
    protected Request1.Head head = new Head();
    @XmlElement(name = "BODY", required = true)
    protected Request1.Body body = new Body();
    @XmlElement(name = "SIGNATURE", required = true)
    protected String signature;

    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = { "credtential", "signdata", "signtype" })
    @Data
    public static class Body {

        @XmlElement(name = "CREDTENTIAL", required = true)
        protected String credtential;
        @XmlElement(name = "SIGN_DATA", required = true)
        protected String signdata;
        @XmlElement(name = "SIGN_TYPE", required = true)
        protected String signtype;

    }

    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = { "txncd", "sessionid", "plat", "ua", "version", "pluginver", "nettype", "mcid", "mca", "imei", "imsi",
            "source", "devid", "serlno" })
    @Data
    public static class Head {

        @XmlElement(name = "TXNCD", required = true)
        protected String txncd;
        @XmlElement(name = "SESSIONID", required = true)
        protected String sessionid;
        @XmlElement(name = "PLAT", required = true)
        protected String plat;
        @XmlElement(name = "UA", required = true)
        protected String ua;
        @XmlElement(name = "VERSION", required = true)
        protected String version;
        @XmlElement(name = "PLUGINVER", required = true)
        protected String pluginver;
        @XmlElement(name = "NETTYPE", required = true)
        protected String nettype;
        @XmlElement(name = "MCID", required = true)
        protected String mcid;
        @XmlElement(name = "MCA", required = true)
        protected String mca;
        @XmlElement(name = "IMEI", required = true)
        protected String imei;
        @XmlElement(name = "IMSI", required = true)
        protected String imsi;
        @XmlElement(name = "SOURCE", required = true)
        protected String source;
        @XmlElement(name = "DEVID", required = true)
        protected String devid;
        @XmlElement(name = "SERLNO", required = true)
        protected String serlno;

    }

}
