//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.05 at 12:29:50 PM CST 
//

package shop;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import lombok.Data;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "head", "body" })
@XmlRootElement(name = "ROOT")
@Data
public class Response1 {

    @XmlElement(name = "HEAD", required = true)
    protected Response1.Head head;
    @XmlElement(name = "BODY", required = true)
    protected Response1.Body body;

    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = { "mblno", "usrno", "errorInfo" })
    @Data
    public static class Body {

        @XmlElement(name = "MBL_NO")
        protected String mblno;
        @XmlElement(name = "USR_NO")
        protected String usrno;
        @XmlElement(name = "ERRORINFO")
        protected String errorInfo;

    }

    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = { "rspcd", "logid", "sessionid" })
    @Data
    public static class Head {

        @XmlElement(name = "RSPCD")
        protected String rspcd;
        @XmlElement(name = "LOGID", required = true)
        protected String logid;
        @XmlElement(name = "SESSIONID", required = true)
        protected String sessionid;

    }

}
